package task

// Type ...
type Type string

// OutputType ...
type OutputType string

const (
	// BoolType ...
	BoolType Type = "bool"
	// StringType ...
	StringType Type = "string"
	// NumberType ...
	NumberType Type = "number"

	// FileOutput ...
	FileOutput OutputType = "file"
	// FolderOutput ...
	FolderOutput OutputType = "folder"

	// VariadicPrefix ...
	VariadicPrefix string = "..."
	// ArrayPrefix ...
	ArrayPrefix string = "[]"
)
